export const sampleExistentialismMap = {
  summary:
    "Existentialism is a philosophical movement that emerged in the late 19th and early 20th centuries, emphasizing individual existence, freedom, and choice. It focuses on the human condition and the search for meaning in an apparently meaningless universe. Key figures include Søren Kierkegaard, Friedrich Nietzsche, Jean-Paul Sartre, and Simone de Beauvoir, who explored themes of authenticity, absurdity, freedom, and responsibility through various works and concepts.",
  nodes: [
    {
      id: "existentialism",
      label: "Existentialism",
      type: "concept",
      description: "A philosophical movement emphasizing individual existence, freedom, and choice.",
      importance: 10,
      discipline: "Philosophy",
      resources: [
        {
          title: "Stanford Encyclopedia of Philosophy: Existentialism",
          url: "https://plato.stanford.edu/entries/existentialism/",
          description: "Comprehensive academic overview of existentialist philosophy",
        },
        {
          title: "Existentialism Is a Humanism by Jean-Paul Sartre",
          description: "Key text that outlines the core principles of existentialist thought",
        },
      ],
    },
    {
      id: "kierkegaard",
      label: "Søren Kierkegaard",
      type: "person",
      description: "Danish philosopher considered the father of existentialism.",
      importance: 9,
      discipline: "Philosophy",
      year: 1813,
      resources: [
        {
          title: "Fear and Trembling",
          description: "Kierkegaard's exploration of faith and the religious life",
        },
        {
          title: "The Concept of Anxiety",
          description: "Analysis of the concept of anxiety and its relationship to freedom",
        },
      ],
    },
    {
      id: "nietzsche",
      label: "Friedrich Nietzsche",
      type: "person",
      description: "German philosopher who explored nihilism and the will to power.",
      importance: 9,
      discipline: "Philosophy",
      year: 1844,
      resources: [
        {
          title: "Thus Spoke Zarathustra",
          description: "Nietzsche's exploration of the Übermensch and eternal recurrence",
        },
        {
          title: "Beyond Good and Evil",
          description: "Critique of traditional morality and truth",
        },
      ],
    },
    {
      id: "sartre",
      label: "Jean-Paul Sartre",
      type: "person",
      description: "French philosopher and playwright who popularized existentialism.",
      importance: 10,
      discipline: "Philosophy",
      year: 1905,
      resources: [
        {
          title: "Being and Nothingness",
          description: "Sartre's major philosophical work on existentialism",
        },
        {
          title: "Existentialism Is a Humanism",
          description: "Lecture that presents existentialism as a form of humanism",
        },
      ],
    },
    {
      id: "beauvoir",
      label: "Simone de Beauvoir",
      type: "person",
      description: "French philosopher, writer, and feminist who explored existentialist ethics.",
      importance: 8,
      discipline: "Philosophy",
      year: 1908,
      resources: [
        {
          title: "The Second Sex",
          description: "Groundbreaking work on feminist existentialism",
        },
        {
          title: "The Ethics of Ambiguity",
          description: "Exploration of existentialist ethics and freedom",
        },
      ],
    },
    {
      id: "camus",
      label: "Albert Camus",
      type: "person",
      description: "French philosopher known for his concept of the absurd.",
      importance: 8,
      discipline: "Philosophy",
      year: 1913,
      resources: [
        {
          title: "The Myth of Sisyphus",
          description: "Essay exploring suicide and the absurd",
        },
        {
          title: "The Stranger",
          description: "Novel exploring themes of absurdity and alienation",
        },
      ],
    },
    {
      id: "heidegger",
      label: "Martin Heidegger",
      type: "person",
      description: "German philosopher who explored being and authenticity.",
      importance: 7,
      discipline: "Philosophy",
      year: 1889,
      resources: [
        {
          title: "Being and Time",
          description: "Heidegger's major work exploring the question of being",
        },
      ],
    },
    {
      id: "authenticity",
      label: "Authenticity",
      type: "concept",
      description: "The idea of being true to oneself and one's choices.",
      importance: 8,
      discipline: "Philosophy",
      resources: [
        {
          title: "Authenticity in Existentialism",
          description: "Overview of the concept of authenticity in existentialist thought",
        },
      ],
    },
    {
      id: "freedom",
      label: "Freedom",
      type: "concept",
      description: "The existentialist concept that humans have radical freedom of choice.",
      importance: 9,
      discipline: "Philosophy",
      resources: [
        {
          title: "Freedom and Responsibility in Existentialist Thought",
          description: "Analysis of the relationship between freedom and responsibility",
        },
      ],
    },
    {
      id: "responsibility",
      label: "Responsibility",
      type: "concept",
      description: "The burden that comes with freedom of choice.",
      importance: 8,
      discipline: "Philosophy",
      resources: [
        {
          title: "Existentialist Ethics",
          description: "Exploration of ethical implications of existentialist freedom",
        },
      ],
    },
    {
      id: "absurd",
      label: "The Absurd",
      type: "concept",
      description: "The conflict between human desire for meaning and the universe's meaninglessness.",
      importance: 7,
      discipline: "Philosophy",
      resources: [
        {
          title: "Camus on the Absurd",
          description: "Analysis of Camus' concept of the absurd",
        },
      ],
    },
    {
      id: "being_and_time",
      label: "Being and Time",
      type: "work",
      description: "Heidegger's major work exploring the question of being.",
      importance: 6,
      discipline: "Philosophy",
      year: 1927,
      resources: [
        {
          title: "Guide to Being and Time",
          description: "Commentary and analysis of Heidegger's major work",
        },
      ],
    },
    {
      id: "being_and_nothingness",
      label: "Being and Nothingness",
      type: "work",
      description: "Sartre's major philosophical work on existentialism.",
      importance: 7,
      discipline: "Philosophy",
      year: 1943,
      resources: [
        {
          title: "Guide to Being and Nothingness",
          description: "Commentary and analysis of Sartre's major work",
        },
      ],
    },
    {
      id: "second_sex",
      label: "The Second Sex",
      type: "work",
      description: "De Beauvoir's groundbreaking work on feminist existentialism.",
      importance: 7,
      discipline: "Philosophy",
      year: 1949,
      resources: [
        {
          title: "The Second Sex and Feminist Existentialism",
          description: "Analysis of de Beauvoir's contribution to feminist philosophy",
        },
      ],
    },
    {
      id: "myth_of_sisyphus",
      label: "The Myth of Sisyphus",
      type: "work",
      description: "Camus' essay exploring suicide and the absurd.",
      importance: 6,
      discipline: "Philosophy",
      year: 1942,
      resources: [
        {
          title: "Analysis of The Myth of Sisyphus",
          description: "Commentary on Camus' exploration of the absurd",
        },
      ],
    },
    {
      id: "existential_phenomenology",
      label: "Existential Phenomenology",
      type: "theory",
      description: "Philosophical approach combining existentialism with phenomenology.",
      importance: 5,
      discipline: "Philosophy",
      resources: [
        {
          title: "Existential Phenomenology: An Introduction",
          description: "Overview of the combination of existentialism and phenomenology",
        },
      ],
    },
    {
      id: "atheistic_existentialism",
      label: "Atheistic Existentialism",
      type: "theory",
      description: "Branch of existentialism that rejects the existence of God.",
      importance: 6,
      discipline: "Philosophy",
      resources: [
        {
          title: "Sartre's Atheistic Existentialism",
          description: "Analysis of Sartre's rejection of God in existentialist thought",
        },
      ],
    },
    {
      id: "religious_existentialism",
      label: "Religious Existentialism",
      type: "theory",
      description: "Branch of existentialism compatible with religious belief.",
      importance: 5,
      discipline: "Philosophy",
      resources: [
        {
          title: "Kierkegaard's Religious Existentialism",
          description: "Analysis of Kierkegaard's integration of faith and existentialism",
        },
      ],
    },
    {
      id: "world_war_ii",
      label: "World War II",
      type: "event",
      description: "Global conflict that influenced existentialist thought.",
      importance: 7,
      discipline: "History",
      year: 1939,
      resources: [
        {
          title: "Existentialism in Post-War Europe",
          description: "The impact of World War II on existentialist philosophy",
        },
      ],
    },
    {
      id: "existentialist_movement",
      label: "Existentialist Movement",
      type: "movement",
      description: "Cultural and intellectual movement centered in Paris in the 1940s-50s.",
      importance: 8,
      discipline: "Philosophy",
      year: 1945,
      resources: [
        {
          title: "The Existentialist Café",
          description: "History of the existentialist movement in post-war Paris",
        },
      ],
    },
  ],
  edges: [
    {
      id: "edge-1",
      source: "kierkegaard",
      target: "existentialism",
      label: "Founded",
      type: "influences",
      strength: 5,
    },
    {
      id: "edge-2",
      source: "nietzsche",
      target: "existentialism",
      label: "Influenced",
      type: "influences",
      strength: 5,
    },
    {
      id: "edge-3",
      source: "sartre",
      target: "existentialism",
      label: "Popularized",
      type: "influences",
      strength: 5,
    },
    {
      id: "edge-4",
      source: "sartre",
      target: "atheistic_existentialism",
      label: "Developed",
      type: "builds_upon",
      strength: 5,
    },
    {
      id: "edge-5",
      source: "kierkegaard",
      target: "religious_existentialism",
      label: "Developed",
      type: "builds_upon",
      strength: 5,
    },
    {
      id: "edge-6",
      source: "sartre",
      target: "being_and_nothingness",
      label: "Wrote",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-7",
      source: "beauvoir",
      target: "second_sex",
      label: "Wrote",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-8",
      source: "camus",
      target: "myth_of_sisyphus",
      label: "Wrote",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-9",
      source: "heidegger",
      target: "being_and_time",
      label: "Wrote",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-10",
      source: "sartre",
      target: "freedom",
      label: "Emphasized",
      type: "builds_upon",
      strength: 4,
    },
    {
      id: "edge-11",
      source: "freedom",
      target: "responsibility",
      label: "Entails",
      type: "builds_upon",
      strength: 4,
    },
    {
      id: "edge-12",
      source: "camus",
      target: "absurd",
      label: "Developed concept of",
      type: "builds_upon",
      strength: 4,
    },
    {
      id: "edge-13",
      source: "heidegger",
      target: "authenticity",
      label: "Explored",
      type: "builds_upon",
      strength: 4,
    },
    {
      id: "edge-14",
      source: "world_war_ii",
      target: "existentialist_movement",
      label: "Catalyzed",
      type: "influences",
      strength: 3,
    },
    {
      id: "edge-15",
      source: "sartre",
      target: "existentialist_movement",
      label: "Led",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-16",
      source: "beauvoir",
      target: "existentialist_movement",
      label: "Key figure in",
      type: "part_of",
      strength: 4,
    },
    {
      id: "edge-17",
      source: "camus",
      target: "existentialist_movement",
      label: "Associated with",
      type: "part_of",
      strength: 3,
    },
    {
      id: "edge-18",
      source: "sartre",
      target: "beauvoir",
      label: "Collaborated with",
      type: "similar_to",
      strength: 3,
    },
    {
      id: "edge-19",
      source: "nietzsche",
      target: "kierkegaard",
      label: "Followed",
      type: "follows",
      strength: 2,
    },
    {
      id: "edge-20",
      source: "atheistic_existentialism",
      target: "religious_existentialism",
      label: "Contrasts with",
      type: "contradicts",
      strength: 4,
    },
    {
      id: "edge-21",
      source: "heidegger",
      target: "existential_phenomenology",
      label: "Developed",
      type: "builds_upon",
      strength: 4,
    },
    {
      id: "edge-22",
      source: "existentialism",
      target: "authenticity",
      label: "Central concept",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-23",
      source: "existentialism",
      target: "freedom",
      label: "Central concept",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-24",
      source: "existentialism",
      target: "responsibility",
      label: "Central concept",
      type: "part_of",
      strength: 5,
    },
    {
      id: "edge-25",
      source: "existentialism",
      target: "absurd",
      label: "Related concept",
      type: "part_of",
      strength: 4,
    },
    {
      id: "edge-26",
      source: "nietzsche",
      target: "authenticity",
      label: "Influenced concept of",
      type: "influences",
      strength: 3,
    },
    {
      id: "edge-27",
      source: "kierkegaard",
      target: "authenticity",
      label: "Early exploration of",
      type: "influences",
      strength: 3,
    },
    {
      id: "edge-28",
      source: "beauvoir",
      target: "freedom",
      label: "Applied to gender",
      type: "applies_to",
      strength: 3,
    },
    {
      id: "edge-29",
      source: "sartre",
      target: "absurd",
      label: "Discussed",
      type: "similar_to",
      strength: 2,
    },
    {
      id: "edge-30",
      source: "heidegger",
      target: "sartre",
      label: "Influenced",
      type: "influences",
      strength: 3,
    },
    {
      id: "edge-31",
      source: "world_war_ii",
      target: "sartre",
      label: "Shaped thinking of",
      type: "influences",
      strength: 2,
    },
    {
      id: "edge-32",
      source: "world_war_ii",
      target: "camus",
      label: "Shaped thinking of",
      type: "influences",
      strength: 2,
    },
    {
      id: "edge-33",
      source: "being_and_nothingness",
      target: "freedom",
      label: "Explores concept of",
      type: "part_of",
      strength: 4,
    },
    {
      id: "edge-34",
      source: "myth_of_sisyphus",
      target: "absurd",
      label: "Explores concept of",
      type: "part_of",
      strength: 4,
    },
  ],
  disciplines: ["Philosophy", "History", "Literature"],
  timespan: {
    start: 1813,
    end: 1960,
  },
}
