CREATE TABLE "maps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" varchar(1024) NOT NULL,
	"node_count" integer DEFAULT 0,
	"edge_count" integer DEFAULT 0,
	"is_public" boolean DEFAULT true,
	"author" varchar(256) NOT NULL,
	"likes" integer DEFAULT 0,
	"views" integer DEFAULT 0,
	"thumbnail" varchar(256),
	"map_data" jsonb,
	"user_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "maps" ADD CONSTRAINT "maps_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;